In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("/Users/tharmmm/Documents/store_sale_project/store-sales-time-series-forecasting/train.csv")
df.head(20)

    id        date  store_nbr               family  sales  onpromotion
0    0  2013-01-01          1           AUTOMOTIVE    0.0            0
1    1  2013-01-01          1            BABY CARE    0.0            0
2    2  2013-01-01          1               BEAUTY    0.0            0
3    3  2013-01-01          1            BEVERAGES    0.0            0
4    4  2013-01-01          1                BOOKS    0.0            0
5    5  2013-01-01          1         BREAD/BAKERY    0.0            0
6    6  2013-01-01          1          CELEBRATION    0.0            0
7    7  2013-01-01          1             CLEANING    0.0            0
8    8  2013-01-01          1                DAIRY    0.0            0
9    9  2013-01-01          1                 DELI    0.0            0
10  10  2013-01-01          1                 EGGS    0.0            0
11  11  2013-01-01          1         FROZEN FOODS    0.0            0
12  12  2013-01-01          1            GROCERY I    0.0            0
13  13  2013-01-01          1           GROCERY II    0.0            0
14  14  2013-01-01          1             HARDWARE    0.0            0
15  15  2013-01-01          1   HOME AND KITCHEN I    0.0            0
16  16  2013-01-01          1  HOME AND KITCHEN II    0.0            0
17  17  2013-01-01          1      HOME APPLIANCES    0.0            0
18  18  2013-01-01          1            HOME CARE    0.0            0
19  19  2013-01-01          1           LADIESWEAR    0.0            0

Create Calendar Features

In [4]:
df["date"] = pd.to_datetime(df["date"])

df["day_of_week"] = df["date"].dt.dayofweek
df["month"] = df["date"].dt.month
df["year"] = df["date"].dt.year
df["week_of_year"] = df["date"].dt.isocalendar().week
df["is_weekend"] = df["day_of_week"].isin([5,6]).astype(int)

In [6]:
df.head()

,id,date,store_nbr,family,sales,onpromotion,day_of_week,month,year,week_of_year,is_weekend
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,1,1,2013,1,0
1,1,2013-01-01,1,BABY CARE,0.0,0,1,1,2013,1,0
2,2,2013-01-01,1,BEAUTY,0.0,0,1,1,2013,1,0
3,3,2013-01-01,1,BEVERAGES,0.0,0,1,1,2013,1,0
4,4,2013-01-01,1,BOOKS,0.0,0,1,1,2013,1,0

In [8]:
df_holiday = pd.read_csv("/Users/tharmmm/Documents/store_sale_project/store-sales-time-series-forecasting/holidays_events.csv")
df_holiday.head()

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False